### ISSUE TITLE
restart of omd-site necessary after insert file "slack"

### ISSUE THREAD

**Issue by nydeggerm** [rmblake/check_mk-slack#13]
Great notification plugin. Thanks a lot!

I've been trying a bit, to get it run.
For my installation (ubuntu, check_mk 1.4.0p8) I needed to run "omd restart" on the command line after insert the file "slack" in the folder "/opt/omd/sites/<site-name>/share/check_mk/notifications/". Otherwise "CMK-Slack Websocket integration" can not be selected (during notification creation). It always disappeared and saved incorrectly.

Maybe you could add this hint ("omd restart") to the file "README.md" in the chapter "HOW TO USE:"? (After Step 2)
I guess this could help other users.

Thanks.

**Comment by rmblake** [comment]
Good spot- documentation updated, thank you.
