### ISSUE TITLE
Notification comment for host downtimes

### ISSUE THREAD

**Issue by nydeggerm** [rmblake/check_mk-slack#15]
Great plugin. Thanks. :-)
I discovered the following: For Downtimes of Services the comment is shown. For Host downtimes only the Author is shown - but twice.

I guess this is because of line 85. It should be like lin 53.

NOW: (the author is two times in the output)
message += "\nTriggered by *" + os.environ['NOTIFY_NOTIFICATIONAUTHOR'] + "* - _" + os.environ['NOTIFY_NOTIFICATIONAUTHOR']  + "_"

NEW:
message += "\nTriggered by *" + os.environ['NOTIFY_NOTIFICATIONAUTHOR'] + "* - _" + os.environ['NOTIFY_NOTIFICATIONCOMMENT']  + "_"

What do you think?

**Comment by rmblake** [comment]
Yes, agreed! Should now be fixed in the latest commit.
